### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by mmuman** [kimholviala/gophernicus#1]
It seems like the main website is now just a redirect to github. The [recipe](https://github.com/haikuports/haikuports/blob/master/net-misc/gophernicus/gophernicus-1.5.recipe) we have at HaikuPort now points to a 404 :-(
Would it be possible to make a release tarball on github so at least we can fix the recipe?

**Comment by hb9kns** [comment]
Hey there, is this issue still open for you? And if yes, what would be the best type of tarball reference? Fixed ones by version, or just a "most recent" one?

**Comment by hb9kns** [comment]
gophernicus.org is up again and under my control, so I can add some fixed location with the most recent stable release tarball. Would a redirection work, or should it be a tarball directly on gophernicus.org?

**Comment by mmuman** [comment]
Any zip or tgz anywhere should be fine, yeah :-)

**Comment by hb9kns** [comment]
I've set up http://gophernicus.org/download/master.zip with the most recent production code.
It should remain a stable and constant URL. Is that ok for you?
Zip is the easiest for the time being, as I can pull it directly from github; but of course I could also locally generate a tarball, if that's better.

**Comment by mmuman** [comment]
Ah, hmm no, I meant it'd be better to have a release, because we check the SHA256 with the one in the recipe, so if the content changes it will break.
See https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/net-misc/gophernicus/gophernicus-1.5.recipe

**Comment by hb9kns** [comment]
Ok, I'll have a look into this. Sorry, new to the party! ^-^
I'll get back to this ASAP.

**Comment by fosslinux** [comment]
On Tue, Mar 05, 2019 at 07:27:34PM -0800, François Revol wrote:
> Ah, hmm no, I meant it'd be better to have a release, because we check the SHA256 with the one in the recipe, so if the content changes it will break.
> See https://github.com/haikuports/haikuports/blob/c2a214e6473117adfdbf84d0f792341b30e1bbd7/net-misc/gophernicus/gophernicus-1.5.recipe
My only concern with this is that gophernicus isn't release-ready yet.
Making it a release might make it seem so.

Currently that would mean for every commit we would have to make a
release, and you would have to continuously update.

Since you seem to be following in the steps of Gentoo, why not make a
Gentoo-style 9999 recipe with a git clone and build from that?

**Comment by mmuman** [comment]
Ok then I suppose I'll just use the commit archives on github and rename the recipe to show version as 1.5~git and increase the revision count when updating it.

**Comment by mmuman** [comment]
Oh… your method of generating a Changelog breaks build with HaikuPorter… because it actually copies the sources elsewhere and does a git init & git commit on it, so we can use git am to apply patches.

**Comment by mmuman** [comment]
Ok, I updated the recipe, I'll have to fix the Makefile someday.

**Comment by fosslinux** [comment]
>  Looks like there are some things to fix anyway, we don't use /boot/common anymore.

Is that in your side or gophernicus?

If there's no further issues, can this be closed?

**Comment by mmuman** [comment]
Well that's the makefile in gophernicus which installs there by default but since I wrote this we added proper package management and ditched this hierarchy. But I'll write a patch for that, so yeah I guess we can close this.
Updated recipe [here](https://github.com/haikuports/haikuports/blob/master/net-misc/gophernicus/gophernicus-2.0%7Egit.recipe).
