### ISSUE TITLE
poor man's HTTP acces

### ISSUE THREAD

**Issue by hb9kns** [kimholviala/gophernicus#12]
Hitting gophernicus (and other gopher servers?) with an HTTP request already works (e.g http://sdf.org:70/ ) and returns the corresponding file or gophermap, which in principle allows to access gophernicus-served content with a stupid modern browser. However, users need to understand gophermaps and must put together new requests, if they want to continue on a link served back by a gophermap.

I was wondering if one could enhance the response to an HTTP request by inserting "real" URLs in some form of bastard HTML notation that would become clickable in browsers. This would allow an easy entry into gopherspace for poor users without decent clients.

However, I don't know whether this would break things or pose security issues, or even result in gopherspace being swamped with stupid HTTP requests?

**Comment by fosslinux** [comment]
Hmmm. Does the current feature generate real HTML or just return the gophermap? I'm currently in the earliest stages of developing a gopher2web application that generates real HTML, in my opinion this should be a separate application entirely. gophernicus is mean to be a gopher server, not a HTML server. In my opinion, keep gopherspace out of HTML and if people want to convert their gopher to html use a completely different application. Just my 2c.

**Comment by hb9kns** [comment]
The current version just returns the plain gophermap, as I see it.

My idea absolutely is *not* to make gopernicus into an HTML server, but explicitly reply to HTTP requests with "crippled" HTML for type 0 and 1 links only, and possibly with some (configurable) header to tell users they're looking at it with the wrong tool (client).

It would allow textual gopher content to be somewhat consumable with HTTP/HTML only clients, with the aim of getting their users to look for a real gopher client. So it's not meant for people to push their gopher content into HTML, but to help them drag more users into the gopher realm.  ^-^

But, and this is important, this gophernicus feature should be configurable by an option and only be triggered by unambiguous HTTP/GET requests (if there's a safe way of defining them).
And if the idea seems to become too complicated or risky, I'll happily abandon it.

**Comment by fosslinux** [comment]
Right, I see. 

> My idea absolutely is not to make gopernicus into an HTML server, but explicitly reply to HTTP requests with "crippled" HTML for type 0 and 1 links only, and possibly with some (configurable) header to tell users they're looking at it with the wrong tool (client).

Do you mean like just <a> tags?

> with the aim of getting their users to look for a real gopher client.

I'm not sure how this would work?

> But, and this is important, this gophernicus feature should be configurable by an option and only be triggered by unambiguous HTTP/GET requests (if there's a safe way of defining them).

of course

**Comment by hb9kns** [comment]
I was thinking a bit more about this, but I ran into some issues:

- it would require replacing most of the `printf` function calls by a special `eprintf` call which would put the line to print by an HTML correspondence
- I don't see how a link to a resource outside of the current gopherhole could be formatted, as the gopher server on the target system most probably would not be able to handle an HTTP request (unless it would also be such a modified/enhanced server

Therefore, I think we should leave this idea as it is, for now, and I'll close it.

**Comment by fosslinux** [comment]
the "gopher server on the _target_ system"? the _target_ system won't have a server, i assume you mean targets are clients?

but at any rate, yeah, they wouldn't be able to handle HTTP requests. Ideally if we were going to implement this it would detect if the client was a client looking for HTTP.

**Comment by hb9kns** [comment]
> the "gopher server on the _target_ system"? the _target_ system won't have a server, i assume you mean targets are clients?

No, I did mean a server:

Assume client C asks server G (running a modified gophernicus) for a gophermap, but with an HTTP request. G replies by sending (my idea of) an HTML-ified file with links understandable for a web browser. For files and folders local to G, this works out well, because G will again send any requested item HTML-ified. But if in the gophermap on G there is a link outside to server N, client C will directly contact N, but that server is a plain gopher server and therefore replies with a normal gopher syntax.
Now the inexperienced user with client C will think the link on *G is broken,* because they cannot access the content on N, while actually their *client is broken.*

Therefore this modified gophernicus would only be helpful for local stuff, not for gopherspace in total.

> but at any rate, yeah, they wouldn't be able to handle HTTP requests. Ideally if we were going to implement this it would detect if the client was a client looking for HTTP.

This would work, but as I said, only help for local stuff.

I admit the idea came from my desire to be able to serve my phlog also to users of stupid webbrowsers, without having to provide a webserver. But that's not really the job of gophernicus. ^-^
