### ISSUE TITLE
Can't make .deb version of Gophernicus because missing dependencies

### ISSUE THREAD

**Issue by spriteclad** [kimholviala/gophernicus#16]
I can't make a .deb copy of the main Gophernicus source because `sudo make deb` is telling me it's missing dependencies, yet it doesn't tell me what they are or where I can get them. Any way to fix this?

**Comment by fosslinux** [comment]
I'll look into this. *spins up container*

**Comment by fosslinux** [comment]
sorry this took so long :fearful: . @spriteclad , it should just be `build-essential` and `dpkg-dev`. Leaving this open to remind me to write docs. setting up Travis CI is giving me a lot of insight hehe

**Comment by fosslinux** [comment]
Documentation has been written. Closing.
