### ISSUE TITLE
Get prologics repository removed

### ISSUE THREAD

**Issue by fosslinux** [kimholviala/gophernicus#21]
Everyone here most likely knows that prologic has a clone of this repository, not a fork, how much far older, at https://github.com/prologic/gophernicus. Can we please get this removed? It is a huge pain, as it comes up first in search results for gophernicus, and is extremely outdated.

@prologic please remove this.

**Comment by prologic** [comment]
> @prologic please remove this.

Done!

I'm really sorry this cause pain and inconvenience! Truth be told I have no idea why I ever had this in the first place (*too long ago to remember*). Apologies once again; it's gone. Hpefully the search indexes catch up soon!

**Comment by fosslinux** [comment]
Thank you very very much. <3

**Comment by fosslinux** [comment]
@prologic actually, would you really mind creating the repository again and just putting a README.md file in it that says "gophernicus is at https://github.com/kimholviala/gophernicus" ? And disable stuff like issues, PRs, etc, just so people notice? For example, Google still dosen't have this repository even on the front page :s

**Comment by prologic** [comment]
Now you're asking a lot! Your original request came across as desparate and in haste. I'm not even sure I have a local copy of what was there. I'll have to search my backups @ home. I'll post back here if I happen to have a backup somewhere.

**Comment by fosslinux** [comment]
Sorry, that wasn't very clear, and I didn't mean to ask of a lot. No, there's no need for a copy of what was there, really what I was asking was this: https://github.com/fosslinux/prologic-gophernicus

**Comment by prologic** [comment]
Done

**Comment by fosslinux** [comment]
Thanks, I'll stop bugging you now. :tada:
